sudo: required
services:
  - docker
env:
  global:
  # Get the current Git SHA
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # From service account credential encryption:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # Download and Install the Google Cloud SDK and install it in our instance:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # Apply config from path.bash.inc file that will modify our shell inside TravisCI:
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Make sure Google Cloud CLI installs kubectl
  - gcloud components update kubectl
  # Authorization with Google Cloud, credentials are stored in service-account.json:
  - gcloud auth activate-service-account --key-file service-account.json
  # Tell the GCloud CLI what PROJECT we want to operate on inside our Google Cloud account:
  - gcloud config set project i-matrix-237912
  # Tell the GCloud CLI what ZONE we want to operate on inside our Google Cloud account:
  - gcloud config set compute/zone us-west1-b
  # Tell the Gloud CLI what cluster it needs to be working with if we issue any set of Kubernetes commands:
  - gcloud container clusters get-credentials multi-cluster
  # Login to Docker using environmental variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Build the test version of multi-client
  - docker build -t rhysgoehring/react-test -f ./client/Dockerfile.dev ./client

script:
  # Define how to run tests for our project
  - docker run rhysgoehring/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master